# POST http://localhost:3000/api/household/654233ed281c7283e1fd4c61/chores
# Content-Type: application/json

# {
#     "name": "2 delete again",
#     "description": "2 delete",
#     "deadline": "2023-11-04",
#     "assignees": "65423397281c7283e1fd4c4c",
#     "household": "654233ed281c7283e1fd4c61"
# }


GET http://localhost:3000/api/household/654233ed281c7283e1fd4c61



# PUT http://localhost:3000/api/household/654233ed281c7283e1fd4c61
# Content-Type: application/json

# {
#     "newName": "Carvalho",
#     "newUsers": [],
#     "newChores": [],

# }


# DELETE http://localhost:3000/api/household/654233ed281c7283e1fd4c61/chores/65429aa64a8f4395200cfdf2

# POST  http://localhost:3006/expenses/new 
# Content-Type: application/json

# {
#     "description": "My second expense",
#     "amount": 12.51,
#     "budgetId": "653bd91a7039c6268e6113dc"
# }
        